### ISSUE TITLE
TacticM Interface

### ISSUE THREAD

**Issue by yangky11** [leanprover-community/duper#7]
Hi,

Does duper have a `TacticM` interface that I can use in metaprogramming (potentially in combination with other `TacticM`)?  

Thanks!

**Comment by JOSHCLUNE** [comment]
Duper doesn't have a `TacticM` interface, but it does have some `MetaM` interfaces in the form of `runDuperPortfolioMode` and `runDuperInstanceN` (for 1 <= N <= 48) in Interface.lean. The `TacticM` monad extends the `MetaM` monad so if you're wanting to call these interfaces from inside the `TacticM` monad, you shouldn't have any issues. `evalDuper` (which implements the `duper` tactic) in Tactic.lean calls these functions so you should be able to see an example of how to call them there.

I'm going to close this issue because I believe that the `MetaM` interface should be usable anywhere a `TacticM` interface would have been, but if I've misunderstood your use case, feel free to reply and I should get a notification.
